import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Shaki',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      //_id: '1',
      name: 'Wedding Decoration-Gold Package',
      slug: 'Decorations',
      category: 'Decorations',
      image: '/images/a1.jpg', // 679px × 829px
      price: 120000,
      countInStock: 10,
      brand: 'VJ-Creations',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality and stylish Stage Background',
    },
    {
      //_id: '2',
      name: 'Personal Bridel Party Makeup for Girls',
      slug: 'Makeup',
      category: 'Makeup',
      image: '/images/a2.jpg',
      price: 75000,
      countInStock: 0,
      brand: 'Evergreen Makeup',
      rating: 4.0,
      numReviews: 10,
      description:
        'Highly recommended makeup for Bridal, Bridal party makeup includes false lash application',
    },
    {
      //_id: '3',
      name: 'DJ Music',
      slug: 'DJ Music',
      category: 'DJ Music',
      image: '/images/a3.jpg',
      price: 65000,
      countInStock: 15,
      brand: 'DJBLACK',
      rating: 4.5,
      numReviews: 14,
      description:
        'Wedding DJs that knows how to create a magical night.entertain your gust to the best',
    },
    {
      //_id: '4',
      name: 'Luxury Wedding Hall with AC ',
      slug: 'Hall',
      category: 'Wedding Hall',
      image: '/images/a4.jpg',
      price: 365000,
      countInStock: 5,
      brand: 'AMARI',
      rating: 4.5,
      numReviews: 10,
      description:
        'The Luxury Wedding Hall at Amari Jaffna Sri Lanka offers a grand and elegant venue for weddings',
    },
    {
      //_id: '5',
      name: 'Outdoor Photography',
      slug: 'photography',
      category: 'photography',
      image: '/images/a1.jpg', // 679px × 829px
      price: 150000,
      countInStock: 10,
      brand: 'VJ-Creations',
      rating: 4.5,
      numReviews: 10,
      description:
        'Capturing moments with artistry and precision, our photography services at VJ-Creations ensure your memories are preserved in stunning detail.',
    },
    {
      //_id: '6',
      name: 'Birthday Card',
      slug: 'Birthday Card',
      category: 'Gifts',
      image: '/images/a2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'VJ-Creations',
      rating: 4.0,
      numReviews: 10,
      description:
        'Send your wishes to your loved ones along with this personalized and heart-warming handmade greeting card.  Your personal message will be hand-written inside of the card.',
    },
    {
      //_id: '7',
      name: 'Church Wedding Decoration',
      slug: 'wedding-deco',
      category: 'Decorations',
      image: '/images/a3.jpg',
      price: 150000,
      countInStock: 15,
      brand: 'VJ-Creations',
      rating: 4.5,
      numReviews: 14,
      description:
        'Feeling for ever Floral Arrangement with a Tough of Elegance for Wedding & All Special Occasions like Church.',
    },
    {
      //_id: '8',
      name: 'Catering',
      slug: 'Catering',
      category: 'Catering',
      image: '/images/a4.jpg',
      price: 45000,
      countInStock: 5,
      brand: 'VJ-Creations',
      rating: 4.5,
      numReviews: 10,
      description:
        'Catering services provide food and beverage provisions for various events and occasions',
    },
    {
      //_id: '6',
      name: 'Birthday Card',
      slug: 'Birthday Card',
      category: 'Gifts',
      image: '/images/a2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'VJ-Creations',
      rating: 4.0,
      numReviews: 10,
      description:
        'Send your wishes to your loved ones along with this personalized and heart-warming handmade greeting card.  Your personal message will be hand-written inside of the card.',
    },
  ],
};
export default data;
